funcx.utils.errors.UserCancelledException
=========================================

.. currentmodule:: funcx.utils.errors

.. autoexception:: UserCancelledException