funcx.utils.errors.FuncXUnreachable
===================================

.. currentmodule:: funcx.utils.errors

.. autoexception:: FuncXUnreachable