funcx.utils.errors.FailureResponse
==================================

.. currentmodule:: funcx.utils.errors

.. autoexception:: FailureResponse